### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [tosinonikute/NotelyVoice#13]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/10326615377

diff log is 1Gb

I've added `add_link_options("LINKER:--build-id=none")` to https://github.com/tosinonikute/NotelyVoice/blob/main/lib/src/main/jni/whisper/CMakeLists.txt#L2 to get rid of 
```
│ │ │ │ -
│ │ │ │ -Displaying notes found in: .note.gnu.build-id
│ │ │ │ -  Owner                Data size       Description
│ │ │ │ -  GNU                  0x00000014      NT_GNU_BUILD_ID (unique build ID bitstring)         Build ID: 89b87adb49f43934bfac7c0abc370c834c03ba63
```

next step, see what's up with:
```
│ │ │ │   The Directory Table (offset 0x1c):
│ │ │ │ -  1    /Users/tosinonikute/AndroidStudioProjects/codelab/NotelyGithubProject/NotelyCompose/lib
│ │ │ │ -  2    /Users/tosinonikute
│ │ │ │ +  1    /home/vagrant/build/com.module.notelycompose.android/lib
│ │ │ │ +  2    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1
│ │ │ │ +  3    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/14.0.7/include
│ │ │ │ +  4    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
│ │ │ │ +  5    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits
│ │ │ │ +  6    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/fortify
│ │ │ │ +  7    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/asm-generic
│ │ │ │ +  8    /opt/android-sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys
│ │ │ │  
│ │ │ │ - The File Name Table (offset 0x89):
│ │ │ │ + The File Name Table (offset 0x30a):
│ │ │ │    Entry        Dir     Time    Size    Name
│ │ │ │    1    1       0       0       src/main/jni/whisper/../src/whisper-arch.h
│ │ │ │ -  2    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__functional_base
│ │ │ │ -  3    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/map
│ │ │ │ -  4    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__tree
│ │ │ │ -  5    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/memory
│ │ │ │ -  6    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/type_traits
│ │ │ │ -  7    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/utility
│ │ │ │ -  8    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/lib64/clang/14.0.7/include/stddef.h
│ │ │ │ -  9    2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__nullptr
│ │ │ │ -  10   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/initializer_list
│ │ │ │ -  11   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__node_handle
│ │ │ │ +  2    2       0       0       __functional_base
│ │ │ │ +  3    2       0       0       map
│ │ │ │ +  4    2       0       0       __tree
│ │ │ │ +  5    2       0       0       memory
│ │ │ │ +  6    2       0       0       type_traits
│ │ │ │ +  7    2       0       0       utility
│ │ │ │ +  8    3       0       0       stddef.h
│ │ │ │ +  9    2       0       0       __nullptr
│ │ │ │ +  10   2       0       0       initializer_list
│ │ │ │ +  11   2       0       0       __node_handle
│ │ │ │    12   1       0       0       src/main/jni/whisper/../ggml/include/ggml.h
│ │ │ │    13   1       0       0       src/main/jni/src/whisper.cpp
│ │ │ │ -  14   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/__string
│ │ │ │ -  15   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string
│ │ │ │ -  16   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view
│ │ │ │ -  17   2       0       0       Library/Android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/iterator
│ │ │ │ +  14   2       0       0       __string
│ │ │ │ +  15   2       0       0       string
│ │ │ │ +  16   2       0       0       string_view
│ │ │ │ +  17   2       0       0       iterator

```

@linsui any ideas?

I guess the APK is built on macOS, right @tosinonikute ?

**Comment by licaon-kter** [comment]
We find that there is a `DependencyInfoBlock` in your APK.

It's a [Signing block](https://source.android.com/docs/security/features/apksigning/v2#apk-signing-block) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

We'll need a new release with this fix.

**Comment by tosinonikute** [comment]
> We find that there is a `DependencyInfoBlock` in your APK.
> 
> It's a [Signing block](https://source.android.com/docs/security/features/apksigning/v2#apk-signing-block) added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).
> 
> While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.
> 
> Could you please disable it with the following code?
> 
> ```
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> We'll need a new release with this fix.

Thanks, this is done: https://github.com/tosinonikute/NotelyVoice/releases/tag/v1.1.2

It was missed during a refactoring recently.

**Comment by licaon-kter** [comment]
thanks

**Comment by licaon-kter** [comment]
a new small diff today:
```
│ │ │ │ │ │   --- androidApp-release-v1.1.3/smali_classes3/com/module/notelycompose/resources/ActualResourceCollectorsKt.smali
│ │ │ │ │ ├── +++ com.module.notelycompose.android_14/smali_classes3/com/module/notelycompose/resources/ActualResourceCollectorsKt.smali
│ │ │ │ │ │┄ Ordering differences only
│ │ │ │ │ │ @@ -238,18 +238,18 @@
│ │ │ │ │ │      new-instance v0, Ljava/util/LinkedHashMap;
│ │ │ │ │ │  
│ │ │ │ │ │      invoke-direct {v0}, Ljava/util/LinkedHashMap;-><init>()V
│ │ │ │ │ │  
│ │ │ │ │ │      check-cast v0, Ljava/util/Map;
│ │ │ │ │ │  
│ │ │ │ │ │      .line 22
│ │ │ │ │ │ +    invoke-static {v0}, Lcom/module/notelycompose/resources/String0_commonMainKt;->_collectCommonMainString0Resources(Ljava/util/Map;)V
│ │ │ │ │ │ -    invoke-static {v0}, Lcom/module/notelycompose/resources/String1_commonMainKt;->_collectCommonMainString1Resources(Ljava/util/Map;)V
│ │ │ │ │ │  
│ │ │ │ │ │      .line 23
│ │ │ │ │ │ +    invoke-static {v0}, Lcom/module/notelycompose/resources/String1_commonMainKt;->_collectCommonMainString1Resources(Ljava/util/Map;)V
│ │ │ │ │ │ -    invoke-static {v0}, Lcom/module/notelycompose/resources/String0_commonMainKt;->_collectCommonMainString0Resources(Ljava/util/Map;)V
│ │ │ │ │ │  
│ │ │ │ │ │      return-object v0
│ │ │ │ │ │  .end method
```

**Comment by tosinonikute** [comment]
> a new small diff today, pls reopen:
> 
> ```
> │ │ │ │ │ │   --- androidApp-release-v1.1.3/smali_classes3/com/module/notelycompose/resources/ActualResourceCollectorsKt.smali
> │ │ │ │ │ ├── +++ com.module.notelycompose.android_14/smali_classes3/com/module/notelycompose/resources/ActualResourceCollectorsKt.smali
> │ │ │ │ │ │┄ Ordering differences only
> │ │ │ │ │ │ @@ -238,18 +238,18 @@
> │ │ │ │ │ │      new-instance v0, Ljava/util/LinkedHashMap;
> │ │ │ │ │ │  
> │ │ │ │ │ │      invoke-direct {v0}, Ljava/util/LinkedHashMap;-><init>()V
> │ │ │ │ │ │  
> │ │ │ │ │ │      check-cast v0, Ljava/util/Map;
> │ │ │ │ │ │  
> │ │ │ │ │ │      .line 22
> │ │ │ │ │ │ +    invoke-static {v0}, Lcom/module/notelycompose/resources/String0_commonMainKt;->_collectCommonMainString0Resources(Ljava/util/Map;)V
> │ │ │ │ │ │ -    invoke-static {v0}, Lcom/module/notelycompose/resources/String1_commonMainKt;->_collectCommonMainString1Resources(Ljava/util/Map;)V
> │ │ │ │ │ │  
> │ │ │ │ │ │      .line 23
> │ │ │ │ │ │ +    invoke-static {v0}, Lcom/module/notelycompose/resources/String1_commonMainKt;->_collectCommonMainString1Resources(Ljava/util/Map;)V
> │ │ │ │ │ │ -    invoke-static {v0}, Lcom/module/notelycompose/resources/String0_commonMainKt;->_collectCommonMainString0Resources(Ljava/util/Map;)V
> │ │ │ │ │ │  
> │ │ │ │ │ │      return-object v0
> │ │ │ │ │ │  .end method
> ```

Added packaging options, hopefully should resolve the issue:

```
android {
    // Force consistent ordering
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
```

**Comment by linsui** [comment]
1.1.5 still has this problem. It generates one of two results randomly.

**Comment by tosinonikute** [comment]
> Same problem for 1.1.7.

Okay I will into why this is happening repeatedly

**Comment by licaon-kter** [comment]
@tosinonikute reading https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/41495 and seeing this kind of unversed variables in the diff log above maybe some proguard rule can help? eg. they used something like this: https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/41495

**Comment by Milliw** [comment]
Still an issue!?
Latest version on F-Droid is 1.1.2 which is quite behind feature wise. :)

**Comment by tosinonikute** [comment]
> https://gitlab.com/fdroid/fdroiddata/-/merge_requests/27244/diffs

Thank you @licaon-kter I just requested that the MR be closed, so I could take some time to fix the issue. It is caused by Language strings added to the project. Then I will create a separate build APK when it's ready. Thanks for your understanding.

**Comment by licaon-kter** [comment]
> I'll have to remove Language files and only stick to english for the F-Droid version.

we have 4000 apps that are all multi language, surely this should not be an issue in the $CURRENTYEAR  😄 

1.1.6 failed already: https://monitor.f-droid.org/builds/log/com.module.notelycompose.android/17#site-footer

**Comment by tosinonikute** [comment]
@licaon-kter 

I have one more idea I'd like to try before I potentially go down the native Android app route.

As v1.1.2 was the last version that actually built successfully on the F-Droid servers (https://github.com/tosinonikute/NotelyVoice/releases/tag/v1.1.2). What I'm thinking is - why don't I create an MR on GitLab using that as my base and see how it performs with both the GitLab CI and F-Droid build servers.

If that works out, I'd have a solid foundation to build on, and I could add new features without touching any of the Gradle stuff or updating dependencies that might break things again.

**Comment by tosinonikute** [comment]
> Still an issue!? Latest version on F-Droid is 1.1.2 which is quite behind feature wise. :)

F-Droid build now live for v1.2.3: https://f-droid.org/en/packages/com.module.notelycompose.android/
